"""Add image field to Question

Revision ID: 0d1725f6e512
Revises: 22d99a5a22e6
Create Date: 2026-01-27 11:07:51.689025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d1725f6e512'
down_revision = '22d99a5a22e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.alter_column('submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('exam_results_reviewed_by_fkey'), type_='foreignkey')
        batch_op.drop_column('total_time_seconds')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('unattempted')
        batch_op.drop_column('incorrect_answers')
        batch_op.drop_column('reviewed_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('incorrect_answers', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unattempted', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reviewed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('exam_results_reviewed_by_fkey'), 'users', ['reviewed_by'], ['id'])
        batch_op.alter_column('submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
