"""Add passcode field to Exam model

Revision ID: 22d99a5a22e6
Revises: 42808a59013b
Create Date: 2026-01-24 19:31:51.660505
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22d99a5a22e6'
down_revision = '42808a59013b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_student_enrollments_class_id'))
        batch_op.drop_index(batch_op.f('idx_student_enrollments_student_id'))

    op.drop_table('student_enrollments')
    op.drop_table('subjects')

    with op.batch_alter_table('performance_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_performance_analytics_user_id'))

    op.drop_table('performance_analytics')
    op.drop_table('student_class_assignments')
    op.drop_table('user_count')

    with op.batch_alter_table('exam_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_exam_submissions_exam_id'))
        batch_op.drop_index(batch_op.f('idx_exam_submissions_student_id'))

    op.drop_table('exam_submissions')

    with op.batch_alter_table('exam_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_exam_enrollments_exam_id'))
        batch_op.drop_index(batch_op.f('idx_exam_enrollments_student_id'))

    op.drop_table('exam_enrollments')
    op.drop_table('subject_count')

    with op.batch_alter_table('true_false_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_true_false_answers_question_id'))

    op.drop_table('true_false_answers')

    with op.batch_alter_table('class_teacher', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])

    # 🔴 FIX STARTS HERE
    # Ensure no NULL values exist before enforcing NOT NULL
    op.execute(
        """
        UPDATE classes
        SET code = 'CLS' || id
        WHERE code IS NULL
        """
    )
    # 🔴 FIX ENDS HERE

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column(
            'code',
            existing_type=sa.VARCHAR(length=50),
            nullable=False
        )
        batch_op.create_index(batch_op.f('ix_classes_name'), ['name'], unique=False)

    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.alter_column(
            'session_code',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=50),
            existing_nullable=False
        )

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.alter_column(
            'passcode',
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=50),
            existing_nullable=True
        )
        batch_op.drop_index(batch_op.f('idx_exams_class_id'))
        batch_op.drop_index(batch_op.f('idx_exams_subject'))
        batch_op.drop_constraint(batch_op.f('fk_exams_class'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])
        batch_op.drop_column('instructions')
        batch_op.drop_column('randomize_questions')
        batch_op.drop_column('randomize_options')

    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_question_options_question_id'))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_questions_exam_id'))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.drop_column('teacher_feedback')

    with op.batch_alter_table('student_classes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_admission_number'))
        batch_op.drop_index(batch_op.f('idx_users_class_id'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_role'))
        batch_op.drop_index(batch_op.f('idx_users_teacher_id'))
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.drop_constraint(batch_op.f('users_admission_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_teacher_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_users_class'), type_='foreignkey')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('role')
        batch_op.drop_column('subject')
        batch_op.drop_column('class_id')
        batch_op.drop_column('admission_number')

    # ### end Alembic commands ###


def downgrade():
    # ⛔ unchanged — your downgrade is already correct
    pass
