"""add branding fields

Revision ID: 4efb27e784ee
Revises: dbb63702d3cb
Create Date: 2026-07-02 21:19:02.236305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4efb27e784ee'
down_revision = 'dbb63702d3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('school_short_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('school_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('school_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('school_website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('school_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('school_logo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('school_favicon', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('primary_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('secondary_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('maintenance_mode', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('footer_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('copyright_text', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('copyright_text')
        batch_op.drop_column('footer_text')
        batch_op.drop_column('timezone')
        batch_op.drop_column('maintenance_mode')
        batch_op.drop_column('secondary_color')
        batch_op.drop_column('primary_color')
        batch_op.drop_column('school_favicon')
        batch_op.drop_column('school_logo')
        batch_op.drop_column('school_address')
        batch_op.drop_column('school_website')
        batch_op.drop_column('school_phone')
        batch_op.drop_column('school_email')
        batch_op.drop_column('school_short_name')
        batch_op.drop_column('school_name')

    # ### end Alembic commands ###
