"""add system_settings table

Revision ID: dbb63702d3cb
Revises: 3cc56a015acb
Create Date: 2026-07-02 20:09:54.481209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb63702d3cb'
down_revision = '3cc56a015acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_terminal',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_constraint(batch_op.f('classes_next_class_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['next_class_id'], ['id'])

    with op.batch_alter_table('promotion_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_promo_history_session'))
        batch_op.drop_index(batch_op.f('idx_promo_history_student'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))

    with op.batch_alter_table('promotion_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_promo_history_student'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_promo_history_session'), ['session_name'], unique=False)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('classes_next_class_id_fkey'), 'classes', ['next_class_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('is_terminal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
