"""Add total_time_seconds to ExamResult

Revision ID: f1d4a03a4e71
Revises: 0d1725f6e512
Create Date: 2026-01-27 12:09:41.811090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d4a03a4e71'
down_revision = '0d1725f6e512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_time_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.drop_column('total_time_seconds')

    # ### end Alembic commands ###
